GET http://localhost:3001/api/v1/questions


###
GET http://localhost:3001/api/v1/scores


###
GET http://localhost:3001/api/v1/topscores

###
POST http://localhost:3001/api/v1/scores
Content-Type: application/json

{
	"name": "Hi",
	"score": 2
}